from pathlib import Path

path = Path('components/evaluation/evaluation-workspace.tsx')
text = path.read_text()

old = '''  const [conditionAnalysisLoading, setConditionAnalysisLoading] =\n    useState(false);'''
new = '''  const [conditionReconOverrideEditing, setConditionReconOverrideEditing] = useState(false);\n  const [conditionAnalysisLoading, setConditionAnalysisLoading] =\n    useState(false);'''
if old not in text:
    raise RuntimeError('state anchor not found')
text = text.replace(old, new, 1)

old = '''                          <div className="text-[10px] font-black uppercase tracking-[0.1em] text-violet-600">AI Recon Planning Reserve</div>\n                          <div className="mt-1 text-2xl font-black text-slate-950">≈ {money(getEffectiveConditionPlanningEstimate())}</div>\n                          <div className="mt-1 text-[10px] font-black text-slate-600">Planning estimate — not a repair quote</div>'''
new = '''                          <div className="text-[10px] font-black uppercase tracking-[0.1em] text-violet-600">AI Recon Planning Reserve</div>\n                          <div className="mt-1 flex items-center gap-2">\n                            {conditionReconOverrideEditing ? (\n                              <div className="flex items-center rounded-lg border border-violet-200 bg-white px-2 py-1">\n                                <span className="text-lg font-black text-slate-500">≈ $</span>\n                                <input\n                                  autoFocus\n                                  type="text"\n                                  inputMode="numeric"\n                                  value={formatNumberInput(getEffectiveConditionPlanningEstimate())}\n                                  onFocus={(event) => event.currentTarget.select()}\n                                  onChange={(event) => {\n                                    setConditionPlanningEstimateOverride(Math.max(0, toNumber(event.target.value)));\n                                    setConditionAnalysisApplied(false);\n                                  }}\n                                  onBlur={() => setConditionReconOverrideEditing(false)}\n                                  onKeyDown={(event) => {\n                                    if (event.key === 'Enter' || event.key === 'Escape') {\n                                      event.currentTarget.blur();\n                                    }\n                                  }}\n                                  className="w-24 bg-transparent px-1 text-2xl font-black text-slate-950 outline-none"\n                                  aria-label="User recon override"\n                                />\n                              </div>\n                            ) : (\n                              <div className="text-2xl font-black text-slate-950">≈ {money(getEffectiveConditionPlanningEstimate())}</div>\n                            )}\n                            <button\n                              type="button"\n                              onClick={() => setConditionReconOverrideEditing(true)}\n                              title="User Recon Override"\n                              aria-label="User Recon Override"\n                              className="grid h-7 w-7 place-items-center rounded-lg border border-slate-200 bg-white text-sm text-slate-500 shadow-sm hover:border-violet-200 hover:text-violet-700"\n                            >\n                              ✎\n                            </button>\n                          </div>\n                          <div className="mt-1 text-[10px] font-black text-slate-600">Planning estimate — not a repair quote</div>'''
if old not in text:
    raise RuntimeError('recon header anchor not found')
text = text.replace(old, new, 1)

path.write_text(text)
print('Added user recon override editor')
