export type MarketComp = {
  id: string;
  included: boolean;
  source: string;
  region?: string;
  regionZip?: string;
  distance: number;
  year: number;
  model: string;
  trim: string;
  mileage: number;
  askingPrice: number;
  qualityScore: number;
  imageUrl?: string | null;
  dealerDays?: number | null;
  marketDays?: number | null;
  equivalenceTier?: "direct" | "near" | "supporting" | "reject";
  equivalenceReasons?: string[];
  autoIncludeEligible?: boolean;
  targetClassification?: string | null;
  candidateClassification?: string | null;
  needsClassificationReview?: boolean;

  marketCheckDetails?: {
    vin?: string | null;
    heading?: string | null;
    listingUrl?: string | null;
    sellerType?: string | null;
    dealerName?: string | null;
    dealerPhone?: string | null;
    dealerWebsite?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    exteriorColor?: string | null;
    interiorColor?: string | null;
    bodyType?: string | null;
    drivetrain?: string | null;
    transmission?: string | null;
    fuelType?: string | null;
    engine?: string | null;
    doors?: number | null;
    cylinders?: number | null;
    listingDate?: string | null;
    lastSeenDate?: string | null;
    targetYear?: number | null;
    targetMake?: string | null;
    targetModel?: string | null;
    targetTrim?: string | null;
    targetFuelType?: string | null;
    targetMileage?: number | null;
    listingConfidence?: "Low" | "Medium" | "High";
    compFitFactors?: {
      yearDelta?: number | null;
      yearPreference?: string | null;
      yearPenalty?: number | null;
      mileageDelta?: number | null;
      distanceMiles?: number | null;
      trimAvailable?: boolean;
      originalScore?: number | null;
      equivalenceTier?: "direct" | "near" | "supporting" | "reject";
      equivalenceReasons?: string[];
      autoIncludeEligible?: boolean;
      needsClassificationReview?: boolean;
    };
    raw?: Record<string, unknown>;
  };
};

export type CompConfidence = "Low" | "Medium" | "High";

export type CompSummary = {
  includedCount: number;
  lowAdjusted: number;
  medianAdjusted: number;
  highAdjusted: number;
  averageAdjusted: number;
  fastSaleTarget: number;
  confidence: CompConfidence;
  averageDealerDays: number;
  averageMarketDays: number;
  marketSpeedSignal: "Unknown" | "Fast" | "Normal" | "Slow" | "Very Slow";
  valuationAvailable?: boolean;
  rawIncludedCount?: number;
  excludedOutlierCount?: number;
  directCount?: number;
  nearCount?: number;
  cappedAdjustmentCount?: number;
  lowReliabilityAdjustmentCount?: number;
  confidenceReasons?: string[];
};
