"use client";
import {useMemo,useRef,useState} from "react";
import styles from "./motor-match-map.module.css";
type Listing={vin:string|null;year:number|null;make:string|null;model:string|null;trim:string|null;price:number|null;miles:number|null;dealer:string|null;city:string|null;state:string|null;url:string|null};
type ApiUsage={callsThisUpdate:number;breakdown:Array<{label:string;purpose:string}>};
type CohortResponse={cohort:Listing[];providerTotal:number;cache:{hit:boolean;ttlSeconds:number};apiUsage:ApiUsage};
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const num=(v:number)=>new Intl.NumberFormat("en-US").format(v);
const CURRENT_YEAR=new Date().getFullYear();

export default function MotorMatchMapPage(){
 const [year,setYear]=useState(Math.min(CURRENT_YEAR-2,2024)),[make,setMake]=useState("BMW"),[model,setModel]=useState("M340i"),[trim,setTrim]=useState("xDrive"),[budget,setBudget]=useState(38000),[mileage,setMileage]=useState(40000),[zip,setZip]=useState("29401"),[distance,setDistance]=useState(500),[cohort,setCohort]=useState<Listing[]>([]),[apiUsage,setApiUsage]=useState<ApiUsage>({callsThisUpdate:0,breakdown:[]}),[sessionCalls,setSessionCalls]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(""),[includeNetwork,setIncludeNetwork]=useState(true);
 const cache=useRef(new Map<string,{expiresAt:number;cohort:Listing[]}>());
 const key=[make,model,trim||"*",zip||"national",zip?distance:"all"].map(v=>String(v).trim().toLowerCase()).join("|");
 async function loadMarket(){if(!make.trim()||!model.trim()){setError("Add a make and model first.");return}const existing=cache.current.get(key);if(existing&&existing.expiresAt>Date.now()){setCohort(existing.cohort);setApiUsage({callsThisUpdate:0,breakdown:[]});setError("");return}setLoading(true);setError("");try{const response=await fetch("/api/motor_match",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({make,model,trim,zip,distance})});const payload:CohortResponse=await response.json();if(!response.ok)throw new Error((payload as any)?.error||"Could not load the market.");setCohort(payload.cohort||[]);setApiUsage(payload.apiUsage||{callsThisUpdate:0,breakdown:[]});setSessionCalls(v=>v+(payload.apiUsage?.callsThisUpdate||0));cache.current.set(key,{cohort:payload.cohort||[],expiresAt:Date.now()+(payload.cache?.ttlSeconds||1800)*1000})}catch(cause){setError(cause instanceof Error?cause.message:"Could not load the market.")}finally{setLoading(false)}}
 const usable=useMemo(()=>cohort.filter(l=>typeof l.price==="number"&&typeof l.miles==="number"),[cohort]);
 const sameYear=useMemo(()=>usable.filter(l=>l.year===year),[usable,year]);
 const matches=useMemo(()=>sameYear.filter(l=>(l.price??Infinity)<=budget&&(l.miles??Infinity)<=mileage),[sameYear,budget,mileage]);
 const maxPrice=Math.max(60000,...sameYear.map(l=>l.price||0),budget*1.18),maxMiles=Math.max(100000,...sameYear.map(l=>l.miles||0),mileage*1.3),minPrice=Math.max(0,(Math.min(10000,...sameYear.map(l=>l.price||Infinity).filter(Number.isFinite))||10000)*.75),minMiles=0;
 const W=1000,H=470,L=72,R=26,T=28,B=54,x=(m:number)=>L+((Math.min(Math.max(m,minMiles),maxMiles)-minMiles)/(maxMiles-minMiles))*(W-L-R),y=(p:number)=>T+(1-(Math.min(Math.max(p,minPrice),maxPrice)-minPrice)/(maxPrice-minPrice))*(H-T-B);
 const budgetY=y(budget),mileageX=x(mileage);
 const sorted=useMemo(()=>[...sameYear].sort((a,b)=>(a.miles||0)-(b.miles||0)),[sameYear]);
 const curve=useMemo(()=>{if(sorted.length<3)return"";const pts=[] as Array<{m:number;p:number}>;for(let i=0;i<6;i++){const a=Math.floor(i*sorted.length/6),b=Math.max(a+1,Math.floor((i+1)*sorted.length/6)),s=sorted.slice(a,b);if(!s.length)continue;const ms=s.map(r=>r.miles||0).sort((a,b)=>a-b),ps=s.map(r=>r.price||0).sort((a,b)=>a-b);pts.push({m:ms[Math.floor(ms.length/2)],p:ps[Math.floor(ps.length/2)]})}return pts.map((pt,i)=>(i?"L":"M")+x(pt.m)+","+y(pt.p)).join(" ")},[sorted,maxMiles,maxPrice,minPrice]);
 const priceNeed=useMemo(()=>{const a=sameYear.filter(l=>(l.miles||Infinity)<=mileage&&typeof l.price==="number").map(l=>l.price as number).sort((a,b)=>a-b);return a.length?a[Math.min(4,a.length-1)]:null},[sameYear,mileage]);
 const milesNeed=useMemo(()=>{const a=sameYear.filter(l=>(l.price||Infinity)<=budget&&typeof l.miles==="number").map(l=>l.miles as number).sort((a,b)=>a-b);return a.length?a[Math.min(4,a.length-1)]:null},[sameYear,budget]);
 const verdict=matches.length>=5?"This target works.":matches.length>0?"Possible, but the market is thin.":"No clean intersection yet.";
 return <main className={styles.shell}>
  <header className={styles.topbar}><div className={styles.brand}><span className={styles.mark}>MM</span><div><b>MOTOR MATCH</b><small>MARKET MAP CONCEPT</small></div></div><div className={styles.tools}><div><span>SESSION API</span><strong>{sessionCalls}</strong></div><div><span>LAST UPDATE</span><strong>{apiUsage.callsThisUpdate}</strong></div><a href="/motor_match">VIEW VERSION A ↗</a></div></header>
  <section className={styles.hero}><div><span className={styles.eyebrow}>WHAT CAN YOU ACTUALLY GET?</span><h1>I want a <em>{year} {make} {model} {trim}</em>.</h1></div><button onClick={loadMarket} disabled={loading}>{loading?"LOADING MARKET…":cohort.length?"REFRESH VEHICLE":"SHOW ME THE MARKET →"}</button></section>
  <section className={styles.sentence}><span>Under</span><div><b>{money(budget)}</b><input type="range" min={5000} max={150000} step={500} value={budget} onChange={e=>setBudget(Number(e.target.value))}/></div><span>with fewer than</span><div><b>{num(mileage)} miles</b><input type="range" min={5000} max={200000} step={1000} value={mileage} onChange={e=>setMileage(Number(e.target.value))}/></div><span>within</span><select value={distance} onChange={e=>setDistance(Number(e.target.value))}><option value={100}>100 mi</option><option value={250}>250 mi</option><option value={500}>500 mi</option><option value={1000}>1,000 mi</option></select><span>of</span><input className={styles.zip} value={zip} onChange={e=>setZip(e.target.value.replace(/\D/g,"").slice(0,5))}/></section>
  <section className={styles.carRow}><label><span>YEAR</span><input type="number" value={year} min="1990" max={CURRENT_YEAR+1} onChange={e=>setYear(Number(e.target.value))}/></label><label><span>MAKE</span><input value={make} onChange={e=>setMake(e.target.value)}/></label><label><span>MODEL</span><input value={model} onChange={e=>setModel(e.target.value)}/></label><label><span>TRIM</span><input value={trim} onChange={e=>setTrim(e.target.value)}/></label><label className={styles.check}><input type="checkbox" checked={includeNetwork} onChange={e=>setIncludeNetwork(e.target.checked)}/><span>Include cars from Mindful's auctions and dealer network</span></label></section>
  <section className={styles.mapCard}><div className={styles.mapTop}><div><span>{sameYear.length} CARS IN MARKET SET</span><h2>{verdict}</h2><p>{matches.length} currently fall inside your price + mileage box.</p></div><div className={styles.legend}><span><i className={styles.dotPublic}/> Public listing</span><span><i className={styles.dotMatch}/> Your match</span><span><i className={styles.dash}/> Typical price</span></div></div>
  {cohort.length?<div className={styles.chartWrap}><svg viewBox={"0 0 "+W+" "+H} className={styles.chart}><rect x={L} y={T} width={mileageX-L} height={budgetY-T} className={styles.targetZone}/>{[0,.25,.5,.75,1].map((t,i)=>{const yy=T+t*(H-T-B),val=maxPrice-t*(maxPrice-minPrice);return <g key={"y"+i}><line x1={L} x2={W-R} y1={yy} y2={yy} className={styles.gridLine}/><text x={L-10} y={yy+4} textAnchor="end" className={styles.axisText}>{money(val)}</text></g>})}{[0,.25,.5,.75,1].map((t,i)=>{const xx=L+t*(W-L-R),val=minMiles+t*(maxMiles-minMiles);return <g key={"x"+i}><line x1={xx} x2={xx} y1={T} y2={H-B} className={styles.gridLine}/><text x={xx} y={H-22} textAnchor="middle" className={styles.axisText}>{Math.round(val/1000)}k</text></g>})}{curve?<path d={curve} className={styles.curve}/>:null}<line x1={L} x2={W-R} y1={budgetY} y2={budgetY} className={styles.limitLine}/><line x1={mileageX} x2={mileageX} y1={T} y2={H-B} className={styles.limitLine}/><text x={W-R-4} y={budgetY-8} textAnchor="end" className={styles.limitLabel}>YOUR PRICE · {money(budget)}</text><text x={mileageX+8} y={T+14} className={styles.limitLabel}>YOUR MILES · {num(mileage)}</text>{sameYear.map((l,i)=>{const ok=(l.price||Infinity)<=budget&&(l.miles||Infinity)<=mileage;return <a key={l.vin||i} href={l.url||undefined} target={l.url?"_blank":undefined} rel="noreferrer"><circle cx={x(l.miles||0)} cy={y(l.price||0)} r={ok?7:5} className={ok?styles.matchDot:styles.publicDot}><title>{[l.year,l.make,l.model,l.trim].filter(Boolean).join(" ")} · {l.price?money(l.price):""} · {l.miles?num(l.miles)+" mi":""}</title></circle></a>})}</svg></div>:<div className={styles.empty}>Choose the vehicle, then load the market to see the price/mileage landscape.</div>}
  <div className={styles.actions}><div className={styles.result}><span>YOUR BOX</span><strong>{matches.length} cars</strong><small>≤ {money(budget)} · ≤ {num(mileage)} mi</small></div><button disabled={!priceNeed||priceNeed<=budget} onClick={()=>priceNeed&&setBudget(Math.ceil(priceNeed/500)*500)}><span>KEEP MILES</span><strong>{priceNeed&&priceNeed>budget?money(priceNeed):"Already works"}</strong><small>Budget needed for a healthier pool</small></button><button disabled={!milesNeed||milesNeed<=mileage} onClick={()=>milesNeed&&setMileage(Math.ceil(milesNeed/1000)*1000)}><span>KEEP PRICE</span><strong>{milesNeed&&milesNeed>mileage?num(milesNeed)+" mi":"Already works"}</strong><small>Mileage needed for a healthier pool</small></button></div></section>
  {error?<div className={styles.error}>{error}</div>:null}
 </main>
}